[package]
name = "pixtools"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
reqwest = { version = "0.12.22", features = ["blocking"] }
tokio = { version = "1.47.1", features = ["full"] }
